
 export const simpleMatchStyle = {
  wrapper: 'w-full flex flex-col gap-3 px-3 pb-3',
  card: 'w-[1120px] min-w-[1120px] h-[152px] rounded-xl border overflow-hidden',
  leftCard: 'w-[70%] h-full flex flex-col px-3 py-2',
  rightCard: 'w-[30%] h-full border-l flex items-center px-2.5',
  singleHead: 'w-full h-[85%] flex items-center gap-[15px]',
  singleBottom: 'w-full h-[15%] flex items-center text-xs text-muted-foreground',
  leftHead: 'w-[30%] h-full flex flex-col items-center justify-center gap-2',
  rightHead: 'w-[70%] h-full flex items-center justify-between gap-3',
  heroIconWrap: 'w-[68px] h-[68px] rounded-xl p-[1px]',
  heroIcon: 'w-full h-full rounded-[10px] object-cover',
  winOrLose: 'text-sm font-bold tracking-wide',
  spellAndRune: 'flex items-center gap-2',
  spellCol: 'flex flex-col gap-1',
  spellIcon: 'w-6 h-6 rounded-md object-cover bg-black/20',
  classicRune: 'flex items-center gap-1',
  kiwiRune: 'flex items-center gap-1',
  runeIcon: 'w-6 h-6 rounded-md object-cover bg-black/20',
  kiwiIcon: 'w-7 h-7 rounded-md object-cover bg-black/20',
  kiwiPlaceholder:
    'w-7 h-7 rounded-md bg-black/20 dark:bg-black/40 border border-black/10 dark:border-white/10',
  KDA_Card: 'w-[110px] h-full flex items-center justify-center',
  DAMAGE_Card: 'w-[110px] h-full flex items-center justify-center',
  CS_Card: 'w-[92px] h-full flex items-center justify-center',
  kad: 'flex flex-col items-center leading-none',
  kadNumber: 'text-base font-semibold',
  subText: 'text-[11px] text-muted-foreground mt-1',
  damage: 'flex flex-col items-center leading-none',
  DamageNumber_Per: 'text-xs text-muted-foreground',
  DamageNumber: 'text-sm font-semibold text-red-500',
  CSNumber: 'text-sm font-semibold',
  CSNumber_Per: 'text-xs text-muted-foreground mt-1',
  epicBox: 'w-[45%] h-full flex items-center content-start gap-1.5 flex-wrap pr-2',
  summonerTag:
    'w-[55%] h-full rounded-lg border border-border/70 bg-background/70 dark:bg-background/40 flex items-center justify-center text-xs text-muted-foreground',
  epicIcon: 'w-7 h-7 rounded-md object-cover',
  placeHolder:
    'w-7 h-7 rounded-md bg-black/20 dark:bg-black/40 border border-black/10 dark:border-white/10',
  epicCard: 'w-[340px] p-2 rounded-lg border border-border bg-popover text-popover-foreground',
  epicHead: 'w-full flex items-start gap-2',
  epicHeadLeft: 'w-10 h-10 rounded-md overflow-hidden shrink-0',
  epicHeadRight: 'flex flex-col gap-1',
  epicName: 'text-sm font-semibold',
  totalPrice: 'text-xs text-muted-foreground',
  epicHeadBottom: 'mt-2 flex items-start justify-between gap-3',
  fromWhichItem: 'flex flex-wrap gap-1',
  fromItem: 'w-6 h-6 rounded overflow-hidden',
  toWhichItem: 'flex flex-wrap gap-1',
  toItem: 'w-6 h-6 rounded overflow-hidden',
  epicBottom: 'mt-2 text-xs leading-4',
  rarityBadge: 'inline-flex items-center gap-1.5 text-xs',
  rarityDot: 'inline-block w-2.5 h-2.5 rounded-full'
}

